resolver: 'lts-21.7'
packages:
- '.'
extra-deps:
- 'hakyll-4.15.1.1'
nix:
  packages:
  - graphviz
  - imagemagick
  # - texlive.combined.scheme-full  # Just for `standalone.cls`.
  - zlib
  - openssh
  - rsync
